FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y \
        openjdk-21-jdk \
            git \
                wget \
                    unzip && \
                        rm -rf /var/lib/apt/lists/*